FROM ubi8/ubi:8.5

MAINTAINER vinhlx90 <vinhlx90@icloud.com>

ENV PORT 8080

RUN yum install -y httpd && yum clean all

##If change the port listening from 80 to other then must to change its value in httpd config file "httpd.conf"
RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/

USER apache

# Expose the custom port that you provided in the ENV var
EXPOSE ${PORT}
# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html) 
COPY ./src/ /var/www/html/
# Start Apache in the foreground
CMD ["httpd", "-D", "FOREGROUND"]
